import { db } from "./index";
import { timelineEvents, chapters, characters, organizations } from "../schema";
import { eq, asc, and } from "drizzle-orm";

export type TimelineEvent = {
	id: string;
	projectId: string | null;
	title: string;
	description: string | null;
	inStoryDate: string | null;
	dateOrder: number;
	entityType: string | null;
	entityId: string | null;
	eventType: string;
	chapterId: string | null;
	metadata: Record<string, unknown> | null;
	autoGenerated: boolean;
	createdAt: Date;
	updatedAt: Date;
};

export type NewTimelineEvent = Omit<TimelineEvent, "createdAt" | "updatedAt" | "autoGenerated">;

function parseEvent(row: Record<string, unknown>): TimelineEvent {
	return {
		...row,
		autoGenerated: !!row.autoGenerated,
		metadata: row.metadata ? JSON.parse(row.metadata as string) : null,
	} as TimelineEvent;
}

export async function getEventsByProject(projectId: string): Promise<TimelineEvent[]> {
	const rows = await db
		.select()
		.from(timelineEvents)
		.where(eq(timelineEvents.projectId, projectId))
		.orderBy(asc(timelineEvents.dateOrder));
	return rows.map(parseEvent);
}

export async function getEventById(id: string): Promise<TimelineEvent | undefined> {
	const result = await db.select().from(timelineEvents).where(eq(timelineEvents.id, id));
	if (!result[0]) return undefined;
	return parseEvent(result[0]);
}

export async function createEvent(event: NewTimelineEvent): Promise<TimelineEvent> {
	const now = new Date();
	const newEvent = {
		...event,
		metadata: event.metadata ? JSON.stringify(event.metadata) : null,
		autoGenerated: false,
		createdAt: now,
		updatedAt: now,
	};
	await db.insert(timelineEvents).values(newEvent);
	return {
		...newEvent,
		metadata: event.metadata || null,
		autoGenerated: false,
	} as TimelineEvent;
}

export async function updateEvent(id: string, data: Partial<NewTimelineEvent>): Promise<TimelineEvent | undefined> {
	const updateData: Record<string, unknown> = { updatedAt: new Date() };
	if (data.title !== undefined) updateData.title = data.title;
	if (data.description !== undefined) updateData.description = data.description;
	if (data.inStoryDate !== undefined) updateData.inStoryDate = data.inStoryDate;
	if (data.dateOrder !== undefined) updateData.dateOrder = data.dateOrder;
	if (data.entityType !== undefined) updateData.entityType = data.entityType;
	if (data.entityId !== undefined) updateData.entityId = data.entityId;
	if (data.eventType !== undefined) updateData.eventType = data.eventType;
	if (data.chapterId !== undefined) updateData.chapterId = data.chapterId;
	if (data.metadata !== undefined) updateData.metadata = data.metadata ? JSON.stringify(data.metadata) : null;

	await db.update(timelineEvents).set(updateData).where(eq(timelineEvents.id, id));
	return getEventById(id);
}

export async function deleteEvent(id: string): Promise<void> {
	await db.delete(timelineEvents).where(eq(timelineEvents.id, id));
}

export async function autoGenerateEvents(projectId: string): Promise<number> {
	let count = 0;

	const existingAuto = await db
		.select({ id: timelineEvents.id })
		.from(timelineEvents)
		.where(and(eq(timelineEvents.projectId, projectId), eq(timelineEvents.autoGenerated, true)));

	const existingAutoIds = new Set(existingAuto.map((r) => r.id));

	const chapterRows = await db
		.select()
		.from(chapters)
		.where(eq(chapters.projectId, projectId))
		.orderBy(asc(chapters.orderIndex));

	const charRows = await db
		.select()
		.from(characters)
		.where(eq(characters.projectId, projectId))
		.orderBy(asc(characters.name));

	const orgRows = await db
		.select()
		.from(organizations)
		.where(eq(organizations.projectId, projectId))
		.orderBy(asc(organizations.name));

	for (const chapter of chapterRows) {
		const existingId = existingAutoIds.has(chapter.id) ? chapter.id : null;
		if (!existingId || !existingAutoIds.has(chapter.id)) {
			const eventId = existingId || crypto.randomUUID();
			await db
				.insert(timelineEvents)
				.values({
					id: eventId,
					projectId,
					title: chapter.title,
					description: null,
					inStoryDate: null,
					dateOrder: chapter.orderIndex,
					entityType: null,
					entityId: null,
					eventType: "chapter",
					chapterId: chapter.id,
					metadata: null,
					autoGenerated: true,
					createdAt: new Date(),
					updatedAt: new Date(),
				})
				.onConflictDoUpdate({ target: timelineEvents.id, set: { title: chapter.title, dateOrder: chapter.orderIndex, updatedAt: new Date() } });
			count++;
		} else {
			existingAutoIds.delete(chapter.id);
		}
	}

	for (const ch of charRows) {
		const eventId = `auto-char-${ch.id}`;
		const existingId = existingAutoIds.has(eventId) ? eventId : null;
		if (!existingId || !existingAutoIds.has(eventId)) {
			await db
				.insert(timelineEvents)
				.values({
					id: eventId,
					projectId,
					title: `Character introduced: ${ch.name}`,
					description: null,
					inStoryDate: null,
					dateOrder: -1000,
					entityType: "character",
					entityId: ch.id,
					eventType: "character_introduction",
					chapterId: null,
					metadata: null,
					autoGenerated: true,
					createdAt: ch.createdAt,
					updatedAt: new Date(),
				})
				.onConflictDoUpdate({ target: timelineEvents.id, set: { title: `Character introduced: ${ch.name}`, updatedAt: new Date() } });
			count++;
		} else {
			existingAutoIds.delete(eventId);
		}
	}

	for (const org of orgRows) {
		const eventId = `auto-org-${org.id}`;
		const existingId = existingAutoIds.has(eventId) ? eventId : null;
		if (!existingId || !existingAutoIds.has(eventId)) {
			await db
				.insert(timelineEvents)
				.values({
					id: eventId,
					projectId,
					title: `Organization founded: ${org.name}`,
					description: null,
					inStoryDate: null,
					dateOrder: -999,
					entityType: "organization",
					entityId: org.id,
					eventType: "organization_founding",
					chapterId: null,
					metadata: null,
					autoGenerated: true,
					createdAt: org.createdAt,
					updatedAt: new Date(),
				})
				.onConflictDoUpdate({ target: timelineEvents.id, set: { title: `Organization founded: ${org.name}`, updatedAt: new Date() } });
			count++;
		} else {
			existingAutoIds.delete(eventId);
		}
	}

	for (const id of existingAutoIds) {
		await db.delete(timelineEvents).where(eq(timelineEvents.id, id));
	}

	return count;
}
